apiVersion: "cert-manager.io/v1"
kind: Certificate
metadata:
  name: wildcard-dev-example-com
  namespace: cert-manager
spec:
  secretName: wildcard-dev-example-com
  duration: 2160h # 90d
  renewBefore: 480h # 20d
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: "kubed=dev-example-com"
  usages:
    - server auth
  dnsNames:
    - '*.dev.example.com'
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
